/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dae2fd",
        "secondary-fixed-dim": "#80d5cb",
        "primary-fixed-dim": "#68dba9",
        "on-error": "#ffffff",
        "on-surface": "#131b2e",
        "surface-tint": "#006c4a",
        "outline-variant": "#bccac0",
        "on-secondary-fixed": "#00201d",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005137",
        "surface-container": "#eaedff",
        "tertiary-fixed": "#68fcbf",
        "tertiary-fixed-dim": "#45dfa4",
        "background": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "secondary": "#006a63",
        "on-primary-container": "#f5fff7",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f5fff7",
        "inverse-primary": "#68dba9",
        "inverse-surface": "#283044",
        "on-primary-fixed": "#002114",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "secondary-container": "#99efe5",
        "primary": "#006948",
        "surface": "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "primary-container": "#00855d",
        "inverse-on-surface": "#eef0ff",
        "primary-fixed": "#85f8c4",
        "secondary-fixed": "#9cf2e8",
        "on-surface-variant": "#3d4a42",
        "on-secondary-fixed-variant": "#00504a",
        "on-tertiary-fixed": "#002114",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-dim": "#d2d9f4",
        "outline": "#6d7a72",
        "on-primary-fixed-variant": "#005137",
        "tertiary-container": "#00855d",
        "surface-bright": "#faf8ff",
        "tertiary": "#006949",
        "on-secondary-container": "#006f67"
      }
    },
  },
  plugins: [],
}
